### ISSUE TITLE
hsb type not suported in generic template

### ISSUE THREAD

**Issue by blairfancy** [TheAgentK/tuyaapi_mqtt#88]
**Describe the bug**
When creating device that include hsb type of data tuya-mqtt crash with error:
`tuya-mqtt:info Exit code: TypeError: Cannot read properties of undefined (reading 'val')`

**To Reproduce**
1. add generic device in devices.conf with topic type hsb
2. start tuya-mqtt

**first debug level**
in tuya-devices.js line 288
`state.push((components[i] === 's' && this.dps[this.config.dpsMode].val === 'white') ? 0 : this.color[components[i]])`

for generic devices dspMode does not exist since template proerty is used.
but even by commenting this line color is allway set to 0,0,0

**Comment by tsightler** [comment]
This project has no active maintainer, and no one has volunteered in 4 years, so it's basically dead.  Open issues will not be addressed.
